INSERT INTO UNIVERSIDAD (acronimo, nombre) VALUES
('UGMA', 'Universidad Gran Mariscal de Ayacucho'),
('UBA', 'Universidad Bicentenaria de Aragua'),
('UNELLEZ', 'Universidad Nacional Experimental de los Llanos Ezequiel Zamora'),
('USI', 'Universidad Santa Ines'),
('UNEG', 'Universidad Nacional Experimental de Guayana'),
('UC', 'Universidad de Carabobo'),
('UNITEC', 'Universidad Tecnologica del Centro'),
('UJAP', 'Universidad Jose Antonio Paez'),
('UAM', 'Universidad Arturo Michelena'),
('UPV', 'Universidad Politecnica de Valencia'),
('UNIPAP', 'Universidad Panamericana del Puerto'),
('IVIC', 'Instituto Venezolano de Investigaciones Cientificas'),
('UCV', 'Universidad Central de Venezuela'),
('USB', 'Universidad Simon Bolivar'),
('UPEL', 'Universidad Pedagogica Experimental Libertador'),
('UNEFA', 'Universidad Nacional Experimental Politecnica de la Fuerza Armada Bolivariana'),
('UNA', 'Universidad Nacional Abierta'),
('UNEXPO', 'Universidad Nacional Experimental Politecnica'),
('UNIMET', 'Universidad Metropolitana'),
('UCAB', 'Universidad Catolica Andres Bello'),
('UAH', 'Universidad Alejandro Humboldt'),
('UJMV', 'Universidad Jose Maria Vargas'),
('LUV', 'La Universidad Virtual Latinoamericana'),
('UMA', 'Universidad Monteavila'),
('UCSAR', 'Universidad Catolica Santa Rosa'),
('IESA', 'Instituto de Estudios Superiores de Administracion'),
('PSM', 'Instituto Universitario Politecnico Santiago Marino'),
('IUNP', 'Instituto Universitario de Nuevas Profesiones'),
('IUTAV', 'Instituto Universitario Tecnologico Americo Vespucio'),
('IUTIRLA', 'Instituto Universitario de Tecnologia Industrial Rodolfo Loero Arismendi'),
('ISUM', 'Instituto Superior Universitario de Mercadotecnia'),
('UNEFM', 'Universidad Nacional Experimental Francisco de Miranda'),
('UDEFA', 'Universidad de Falcon'),
('UNERG', 'Universidad Nacional Experimental Romulo Gallegos'),
('UCLA', 'Universidad Lisandro Alvarado'),
('UNY', 'Universidad Yacambu'),
('UFT', 'Universidad Fermin Toro'),
('ULA', 'Universidad de Los Andes'),
('USM', 'Universidad Santa Maria'),
('UNE', 'Universidad Nueva Esparta'),
('UNIMAR', 'Universidad de Margarita'),
('UDO', 'Universidad de Oriente'),
('UVM', 'Universidad Valle del Momboy'),
('UNESR', 'Universidad Nacional Experimental Simon Rodriguez'),
('UNET', 'Universidad Nacional Experimental del Tachira'),
('IUTAI', 'Instituto Universidad de Tecnologia Agro Industrial'),
('UCAT', 'Universidad Catolica del Tachira'),
('UMC', 'Universidad Nacional Experimental Maritima del Caribe'),
('UNEY', 'Universidad Nacional Experimental del Yaracuy'),
('UNERMB', 'Universidad Nacional Experimental Rafael Maria Baralt'),
('LUZ', 'Universidad del Zulia'),
('UNESUR', 'Universidad Nacional Experimental Sur del Lago'),
('UBV', 'Universidad Bolivariana de Venezuela'),
('URBE', 'Universidad Rafael Belloso Chacin'),
('UNICA', 'Universidad Catolica Cecilio Acosta'),
('URU', 'Universidad Rafael Urdaneta'),
('UNIOJEDA', 'Universidad Alonso de Ojeda'),
('UJGH', 'Universidad Dr. Jose Gregorio Hernandez'),
('INTEVEP', 'Instituto Tecnologico Venezolano del Petroleo'),
('HUC', 'Hospital Universitario de Caracas'),
('INIA', 'Instituto Nacional de Investigaciones Agropecuarias'),
('IDEA', 'Instituto de Estudios Avanzados'),
('CIDA', 'Centro de Investigaciones de Astronomia'),
('CMDLT', 'Centro Medico Docente La Trinidad');